### ISSUE TITLE
mesh config "http get" doesn't retry with all resolved addresses

### ISSUE THREAD

**Issue by arlake228** [perfsonar/mesh-config#4]
_From @arlake228 on March 14, 2015 12:41_

Original [issue 1013](https://code.google.com/p/perfsonar-ps/issues/detail?id=1013) created by arlake228 on 2014-11-04T13:31:00.000Z:

If a DNS name resolves to v4 and v6 addresses but v6 is either disabled on the client or unavailable on the server, the mesh config https_get routine, using IO::Socket::INET6 under the hood, will try the v6 address and fail, even though the v4 address is accessible. There is a MultiHomed flag that you can add to the IO::Socket::\* modules, but when we did that, it went into an unhelpful infinite loop with the module version available in RedHat 6. There are a few options to fix this:

1) Find a better Perl module, that's available in RedHat 6 or EPEL6, and rewrite the https_get routine using it
2) Have the https_get routine do the address resolving, and iterate through the addresses itself
3) Package a newer version of the IO::Socket::INET6 module

I'm partial to #&nbsp;1 if there's something we can use, but barring that, #&nbsp;2 seems the way to go. I'd imagine #&nbsp;3 would just lead to all sorts of pain.

_Copied from original issue: perfsonar/project#1011_

**Comment by arlake228** [comment]
Comment [#1](https://code.google.com/p/perfsonar-ps/issues/detail?id=1013#c1) originally posted by arlake228 on 2015-01-27T14:56:11.000Z:

&lt;empty&gt;

**Comment by arlake228** [comment]
Comment [#2](https://code.google.com/p/perfsonar-ps/issues/detail?id=1013#c2) originally posted by arlake228 on 2015-01-27T14:56:24.000Z:

&lt;empty&gt;

**Comment by arlake228** [comment]
Moving this to 3.6, mainly when we move to CentOS 7. There are some newer Perl libraries available in CentOS 7 that make this easier.

**Comment by HakanCalimFau** [comment]
I suggest to use:
http://search.cpan.org/~sullr/Net-INET6Glue-0.5/lib/Net/INET6Glue.pm#SYNOPSIS

it adjust all net modules for IPv6 support. It is used for Prl versions where IPv6 support is not available. In Centos 6 this package is available: perl-Net-INET6Glue

**Comment by arlake228** [comment]
From my perspective it's OK to go ahead with INET6Glue.

**Comment by laeti-tia** [comment]
And it is available for Debian too!

**Comment by HakanCalimFau** [comment]
I cannot reproduce this error. I have a host which is available over IPv4 and IPv6. On my development host I have IPv6 disabled. When I run the mesh config agent (generate_configuration) it works without a error. The regulartesting.conf is created successfully. Not sure maybe I have something misunderstood?

BTW: Where I can enable logging in mesh config?

**Comment by arlake228** [comment]
Are you trying to reach a remote meshconfig that has a hostname in DNS that resolves to both v4 and v6? It's possible this has been fixed by the underlying library since this issue was originally reported.

You can give the generate_configuration script the --verbose flag if you want more output.

**Comment by HakanCalimFau** [comment]
My test scenario:
The mesh config which is accessible remotely on:
<mesh>
    configuration_url           http://ps-toolkit.rrze.uni-erlangen.de/toolkit/meshconfig/fau-mesh-config.json
</mesh>

On the host ps-toolkit.rrze.uni-erlangen.de is IPv6 disabled:
[labor@ps-toolkit ~]$ ifconfig -a
eth0      Link encap:Ethernet  HWaddr 00:0C:29:25:38:AA  
          inet addr:131.188.81.86  Bcast:131.188.81.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:208541601 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2738193 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:10000 
          RX bytes:304770565994 (283.8 GiB)  TX bytes:360295443 (343.6 MiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:857232 errors:0 dropped:0 overruns:0 frame:0
          TX packets:857232 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:537428761 (512.5 MiB)  TX bytes:537428761 (512.5 MiB)

[labor@ps-toolkit ~]$ host ps-toolkit

On the host genesis-vmdev-centos6-32.rrze.uni-erlangen.de is IPv6 and IPv4 enabled. 
[root@genesis-vmdev-centos6-32 unrz217]# ifconfig -a
eth0      Link encap:Ethernet  HWaddr 00:0C:29:92:27:16  
          inet addr:131.188.81.33  Bcast:131.188.81.255  Mask:255.255.255.0
          inet6 addr: 2001:638:a000:3502::21/64 Scope:Global
          inet6 addr: fe80::20c:29ff:fe92:2716/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2208 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1964 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:201944 (197.2 KiB)  TX bytes:151407 (147.8 KiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:68 errors:0 dropped:0 overruns:0 frame:0
          TX packets:68 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:6072 (5.9 KiB)  TX bytes:6072 (5.9 KiB)

[root@genesis-vmdev-centos6-32 unrz217]# 

I checked the DNS for ps-toolkit.rrze.uni-erlangen.de:
[root@genesis-vmdev-centos6-32 unrz217]# host ps-toolkit.rrze.uni-erlangen.de
ps-toolkit.rrze.uni-erlangen.de has address 131.188.81.86
ps-toolkit.rrze.uni-erlangen.de has IPv6 address 2001:638:a000:3502::56
[root@genesis-vmdev-centos6-32 unrz217]# 

Now I start the mesh config agent:

[root@genesis-vmdev-centos6-32 bin]# ./generate_configuration  --verbose
2016/04/05 11:31:48 (1369) DEBUG> perfSONARRegularTesting.pm:167 perfSONAR_PS::MeshConfig::Generators::perfSONARRegularTesting::add_mesh_tests - Adding: Traceroute Test Between FAU hosts
2016/04/05 11:31:48 (1369) DEBUG> perfSONARRegularTesting.pm:167 perfSONAR_PS::MeshConfig::Generators::perfSONARRegularTesting::add_mesh_tests - Adding: OWAMP Test Between FAU hosts
2016/04/05 11:31:48 (1369) DEBUG> perfSONARRegularTesting.pm:167 perfSONAR_PS::MeshConfig::Generators::perfSONARRegularTesting::add_mesh_tests - Adding: BWCTL/iperf3 Test Between FAU hosts
2016/04/05 11:31:48 (1369) DEBUG> Agent.pm:523 perfSONAR_PS::MeshConfig::Agent::__compare_file - Checking for changes in /etc/perfsonar/regulartesting.conf
2016/04/05 11:31:48 (1369) DEBUG> Agent.pm:528 perfSONAR_PS::MeshConfig::Agent::__compare_file - Reading /etc/perfsonar/regulartesting.conf
2016/04/05 11:31:48 (1369) DEBUG> Agent.pm:531 perfSONAR_PS::MeshConfig::Agent::__compare_file - /etc/perfsonar/regulartesting.conf changed
2016/04/05 11:31:48 (1369) DEBUG> Agent.pm:488 perfSONAR_PS::MeshConfig::Agent::__write_file - Writing /etc/perfsonar/regulartesting.conf
2016/04/05 11:31:48 (1369) DEBUG> Agent.pm:174 perfSONAR_PS::MeshConfig::Agent::__send_error_messages - No errors reported
[root@genesis-vmdev-centos6-32 bin]# 

It seems everything is ok. Is this the correct way to test this issue?

**Comment by arlake228** [comment]
I'm having to do a serious memory refresh on this, but I think the problem only manifests itself when both hosts have IPv6 enabled but there is not a clean IPv6 path between the two. That's obviously much harder to test. The best I can think to try to somewhat recreate that scenario is block the port hosting the meshconfig JSON in ip6tables but not iptables. The other option is to mark this as WontFix and just say "specify an IPv4 address in the URL to the mesh JSON" if someone encounters this scenario.

**Comment by candlerb** [comment]
This is still a problem today.

Here, a DNS name points to both v4 and v6 addresses, but the v6 address is currently unreachable:

```
# sudo -u perfsonar /usr/lib/perfsonar/bin/generate_configuration
2016/07/06 12:09:25 (16398) ERROR> Agent.pm:312 perfSONAR_PS::MeshConfig::Agent::__configure_host - Problem with mesh configuration: Problem retrieving https://maddash-config.example.com/maddash-config/maddash.json: IO::Socket::INET6 configuration failederror:00000000:lib(0):func(0):reason(0)
```

The client host has working v6 connectivity, but the target web server currently does not.

It should be very easy to reproduce by adding a name into the DNS with a valid v4 address and a non-existent v6 address.

Obviously the workaround is to create a new name in the DNS which points to v4 only - but then I have to remember to switch this to the correct name when the target AAAA is working.

**Comment by mfeit-internet2** [comment]
@candlerb:  The other workaround would be to remove the AAAA record for the host if it doesn't have any interfaces that can be reached via v6.  Any one looking it up would have no idea whether there's supposed to be something at the other end or if it's just bogus information.

To prevent having to do mass changes to host names, you might consider giving each interface a unique name (e.g., `foo-ipv4.example.com` and `foo-ipv6.example.com`) and making `foo.example.org` a CNAME for whichever is preferred.

(But yes, perfSONAR should be able to sift through all of the addresses and find one that works.)
